name: Flutter Web Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: flutter pub get
        working-directory: UniTest_Elite_Final/frontend_flutter

      - name: Build web
        run: flutter build web --release --base-href "/UNISTEST-ESGUERRA-RUBEN/"
        working-directory: UniTest_Elite_Final/frontend_flutter

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: UniTest_Elite_Final/frontend_flutter/build/web